spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: nextar
    password: nextar
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    user: nextar
    password: nextar
    schemas: calculadora-rest
    url: jdbc:h2:mem:mydb
    enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
logging:
  level:
    root: INFO
    com.carlos.CalculadoraRest: DEBUG
jwt:
  secret: javainuse